language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'

before_script:
  - sudo apt-get update
  - sudo apt-get install ecryptfs-utils
  - sudo modprobe ecryptfs

install:
  - composer install

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
